import { StyleSheet } from "react-native";

export const bottomPanelStyles = StyleSheet.create({
  outerContainer: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 24,
    zIndex: 50,
    elevation: 12,
  },
  panelContainer: {
    backgroundColor: "#F6F3EE",
    borderRadius: 24,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E4DDD3",
  },
  cardsWrapper: {
    gap: 12,
  },
  startCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderWidth: 1.5,
    borderColor: "#E4DDD3",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  destinationCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1.5,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  destinationCardDefaultBorder: {
    borderColor: "#E4DDD3",
  },
  destinationCardFocusedBorder: {
    borderColor: "#B03060",
  },
  startValueText: {
    fontSize: 18,
    fontWeight: "700",
  color: "#B03060",
  },
  cardLabelText: {
    fontSize: 16,
    color: "#9C948B",
  },
  destinationInputWrapper: {
    flex: 1,
  },
  destinationInput: {
    fontSize: 18,
    fontWeight: "700",
    color: "#B03060",
    paddingVertical: 0,
  },
  destinationRightSide: {
    flexDirection: "row",
    alignItems: "center",
  },
  destinationLabel: {
    fontSize: 16,
    color: "#9C948B",
    marginRight: 12,
  },
  arrowButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#B03060",
    alignItems: "center",
    justifyContent: "center",
  },
  resultsContainer: {
    marginTop: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E3DDD4",
    maxHeight: 160,
    overflow: "hidden",
  },
  resultItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0ECE6",
  },
  resultTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#3C3732",
  },
  resultSubtitle: {
    fontSize: 12,
    color: "#8A837A",
    marginTop: 2,
  },
  actionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 14,
  },
  directionsButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ECE6DD",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    opacity: 0.7,
  },
  directionsText: {
    marginLeft: 8,
    color: "#7A746C",
    fontWeight: "600",
  },
  rightActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  exitButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#B03060",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  exitText: {
    marginLeft: 8,
    color: "#FFFFFF",
    fontWeight: "600",
  },
});