import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
  },
  backdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "transparent",
  },
  sheet: {
    borderTopLeftRadius: 45,
    borderTopRightRadius: 45,
    width: "100%",
    alignSelf: "stretch",
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 12,
    marginHorizontal: 0,
    marginBottom: 0,
    minHeight: 300,
    maxHeight: "80%",
    overflow: "hidden",
  },
  dragHandle: {
    width: 38,
    height: 3,
    borderRadius: 999,
    alignSelf: "center",
    marginBottom: 6,
  },
  dragHandleTouchArea: {
    alignSelf: "stretch",
    paddingTop: 4,
    paddingBottom: 6,
  },
  header: {
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    minHeight: 46,
    marginBottom: 6,
  },
  headerSide: {
    position: "absolute",
    top: 0,
    bottom: 0,
    justifyContent: "center",
  },
  headerSideLeft: {
    left: 0,
  },
  headerSideRight: {
    right: 0,
    alignItems: "flex-end",
  },
  headerCenter: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 72,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#B03060",
    textAlign: "center",
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  closeButtonCircle: {
    width: 35,
    height: 35,
    borderRadius: 80,
    alignItems: "center",
    justifyContent: "center",
  },
  closeButtonText: {
    fontSize: 24,
    fontWeight: "300",
    lineHeight: 24,
    includeFontPadding: false,
    textAlign: "center",
  },
  transportRow: {
    flexDirection: "row",
    gap: 0,
    marginBottom: 8,
    borderRadius: 999,
    padding: 4,
  },
  transportButton: {
    flex: 1,
    minWidth: 0,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 4,
    flexDirection: "row",
    gap: 2,
  },
  routeList: {
    marginTop: 2,
    maxHeight: 380,
  },
  routeCard: {
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  durationText: {
    fontSize: 24,
    fontWeight: "700",
    color: "#B03060",
    lineHeight: 26,
  },
  etaText: {
    color: "#C48BA1",
    marginTop: 0,
    fontSize: 14,
    fontWeight: "500",
  },
  routeTransitSummary: {
    color: "#6E6E73",
    marginTop: 2,
    fontSize: 12,
    fontWeight: "600",
  },
  distanceText: {
    color: "#C48BA1",
    marginRight: 10,
    fontWeight: "500",
    fontSize: 14,
  },
  startButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#B03060",
    alignItems: "center",
    justifyContent: "center",
  },
  centerInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  transitSection: {
    marginTop: 6,
    marginBottom: 8,
    gap: 8,
  },
  transitSectionTitle: {
    color: "#B03060",
    fontSize: 16,
    fontWeight: "700",
    marginHorizontal: 2,
  },
  transitCard: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  transitCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  transitLineName: {
    color: "#B03060",
    fontSize: 16,
    fontWeight: "700",
    flexShrink: 1,
    paddingRight: 8,
  },
  transitTypeBadge: {
    backgroundColor: "#ECECEF",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  transitTypeBadgeText: {
    color: "#5F5F63",
    fontSize: 11,
    fontWeight: "700",
  },
  transitHeadsign: {
    color: "#C48BA1",
    fontSize: 13,
    fontWeight: "500",
  },
  transitStops: {
    color: "#6E6E73",
    fontSize: 13,
    fontWeight: "500",
  },
  shuttleBadgeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  shuttleBadgeIcon: {
    backgroundColor: "#B03060",
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 6,
  },
  shuttleBadgeLetter: {
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 12,
  },
  shuttleBadgeText: {
    color: "#B03060",
    fontWeight: "700",
    fontSize: 12,
  },
});
